### ISSUE TITLE
peer-to-peer

### ISSUE THREAD

**Issue by clin2on3mun** [ShaliniNayan/To-Do-List#6]
Hi @ShaliniNayan, good job so far on the to-do list project. Below are some ideas and suggestions about the project, cheers! 👍🏽 

### HIGHLIGHTS 🎯 

- Good implementation of guidelines🥇 

### RECOMMENDATIONS 🤔
-deployment: **npm install gh-pages, open package.json scripts object add "deploy": "gh-page -d dist", "homepage": "https://github.com/supreeti/ToDoList", npm run deploy **

**Comment by ShaliniNayan** [comment]
Thankyou & Noted.
